import Foundation

enum Localization {
    static let languageKey = "app_language"

    private static let table: [String: [String: String]] = [
        "zh": [
            // Tabs
            "tab.today": "今日计划",
            "tab.tasks": "任务",
            "tab.settings": "设置",
            "tab.companion": "伙伴",

            // Dashboard
            "dashboard.title": "今日面板",
            "dashboard.subtitle": "AI-native Todo",
            "dashboard.premiumOn": "高级已开启",
            "dashboard.freeMode": "免费模式",
            "dashboard.subscribed": "订阅有效",
            "dashboard.trialLeft": "试用剩余 %d 天",
            "dashboard.bannerTitle": "AI 今日计划可升级",
            "dashboard.todayPlan": "今日计划",
            "dashboard.aiGenerate": "AI 生成",
            "dashboard.aiGenerateA11y": "AI 生成今日计划",
            "dashboard.regenerate": "重新生成",
            "dashboard.regenerateA11y": "重新生成今日计划",
            "dashboard.emptyPlan": "今天还没有任务，先去任务页添加一条吧。",
            "dashboard.emptyA11y": "任务列表为空",
            "dashboard.subscribe": "订阅",
            "dashboard.execution": "执行态势",
            "dashboard.progress": "完成率 %d%% · 健康分 %d",
            "dashboard.statTotal": "全部任务",
            "dashboard.statActive": "进行中",
            "dashboard.statCompleted": "已完成",
            "dashboard.statHealth": "健康分",
            "dashboard.aiShort": "AI",

            // Tasks
            "tasks.title": "任务",
            "tasks.inboxTag": "Natural language inbox",
            "tasks.headline": "把脑内噪音变成可执行下一步",
            "tasks.inputPlaceholder": "今天想推进什么？",
            "tasks.inputA11y": "任务描述",
            "tasks.taskType": "任务类型",
            "tasks.capture": "捕捉",
            "tasks.captureA11y": "捕捉任务",
            "tasks.expand": "展开高级选项",
            "tasks.collapse": "收起高级选项",
            "tasks.context": "上下文",
            "tasks.acceptance": "验收标准",
            "tasks.prompt": "下一步 Prompt",
            "tasks.priority": "优先级 %d",
            "tasks.minutes": "%d 分钟",
            "tasks.dueDate": "截止日期",
            "tasks.clearDue": "清除截止日期",
            "tasks.listTitle": "任务列表",
            "tasks.clearCompleted": "清除已完成",
            "tasks.clearCompletedA11y": "清除已完成任务",
            "tasks.taskCount": "%d 个任务",
            "tasks.type": "类型",
            "tasks.allTypes": "全部类型",
            "tasks.typeA11y": "按任务类型筛选",
            "tasks.filterA11y": "筛选：%@",
            "tasks.emptyTitle": "任务队列还是空的",
            "tasks.emptyHint": "先捕捉一个目标，我会帮你压成下一步。",
            "tasks.upgrade": "升级",
            "tasks.upgradeA11y": "升级高级功能",

            // Filter
            "filter.all": "全部",
            "filter.active": "进行中",
            "filter.completed": "已完成",
            "filter.high": "高优先级",

            // Task card
            "card.start": "开始",
            "card.complete": "完成",
            "card.done": "已完成",
            "card.archived": "已归档",
            "card.statusTodo": "待开始",
            "card.statusDoing": "进行中",
            "card.statusDone": "已完成",
            "card.statusArchived": "已归档",
            "card.markDone": "标记完成",
            "card.unmarkDone": "取消完成",
            "card.minutes": "%d 分钟",
            "card.updateStatusA11y": "更新状态为%@",
            "card.editA11y": "编辑任务",
            "card.chipContext": "上下文",
            "card.chipAcceptance": "验收标准",
            "card.chipPrompt": "下一步",
            "card.chipSource": "源自：%@",
            "card.archive": "归档",
            "card.delete": "删除",
            "card.a11y": "任务%@，类型%@，优先级%d，%@，估算%d分钟",

            // Settings
            "settings.account": "账号与订阅",
            "settings.trial": "试用",
            "settings.trialDays": "剩余 %d 天",
            "settings.trialEnded": "已结束",
            "settings.premium": "高级",
            "settings.subscribed": "已订阅",
            "settings.notSubscribed": "未订阅",
            "settings.ai": "AI 设置",
            "settings.aiKey": "OpenAI API Key",
            "settings.aiNoKey": "未配置 Key，AI 功能将使用本地规划器。",
            "settings.aiHasKey": "已配置 Key，AI 功能将调用 OpenAI。",
            "settings.obsidian": "Obsidian 导出",
            "settings.generateExport": "生成今日导出",
            "settings.fileName": "文件名",
            "settings.exportLocked": "导出为订阅功能",
            "settings.unlockExport": "订阅解锁高级导出",
            "settings.billing": "账务",
            "settings.restore": "恢复购买",
            "settings.benefits": "高级权益",
            "settings.benefitAI": "AI 计划",
            "settings.benefitExport": "高级导出",
            "settings.benefitAnalytics": "分析看板",
            "settings.status": "状态",
            "settings.shareFile": "分享导出文件",
            "settings.copied": "已复制",
            "settings.copy": "复制到剪贴板",
            "settings.exportTitle": "今日导出",
            "settings.language": "语言 / Language",
            "settings.zh": "中文",
            "settings.en": "English",
            "settings.unlockPremium": "解锁订阅",

            // Common
            "common.cancel": "取消",
            "common.save": "保存",
            "common.done": "完成",

            // Edit
            "edit.title": "编辑任务",
            "edit.titleSection": "标题",
            "edit.titlePlaceholder": "任务标题",
            "edit.details": "详情",
            "edit.plan": "规划",

            // Paywall
            "paywall.title": "解锁专业体验",
            "paywall.trialLeft": "你现在在免费试用期，剩余 %d 天。",
            "paywall.trialEnded": "试用已结束，请订阅以继续使用高级功能。",
            "paywall.perks": "高级权限：AI 今日计划、分析看板、高级导出，一次订阅全部解锁。",
            "paywall.loading": "加载中…",
            "paywall.noProducts": "暂未读取到商品信息，请检查 StoreKit 配置后重试。",
            "paywall.refresh": "刷新商品",
            "paywall.manage": "如需切换/管理订阅，可在 App Store 的订阅设置中完成。",
            "paywall.subscribe": "订阅",
            "paywall.close": "关闭",

            // AI workbench
            "ai.title": "AI 工作台",
            "ai.goal": "目标 / 需求 / 想法",
            "ai.goalA11y": "目标输入",
            "ai.breakdown": "智能拆解",
            "ai.summary": "复盘与下一步",
            "ai.todayPlan": "生成今日计划",
            "ai.output": "AI 输出",
            "ai.outputEmpty": "还没有内容。没有 API Key 时会使用本地规划器；填入 Key 后会调用 OpenAI。",
            "ai.addToTodo": "加入待办 (%d)",

            // AI status
            "ai.status.noGoal": "先输入一个目标或想法。",
            "ai.status.breakdownBusy": "正在调用 AI 拆解...",
            "ai.status.breakdownLocal": "使用本地规划器拆解...",
            "ai.status.saved": "已保存",
            "ai.status.breakdownResult": "已生成 %d 条任务，可一键加入待办。",
            "ai.status.summaryBusy": "正在生成复盘...",
            "ai.status.summaryLocal": "使用本地状态生成复盘...",
            "ai.status.summaryDone": "复盘已生成。",
            "ai.status.planBusy": "正在生成今日计划...",
            "ai.status.planLocal": "使用本地队列生成今日计划...",
            "ai.status.planDone": "今日计划已生成。",
            "ai.status.noImport": "当前没有可导入的 AI 任务。请先执行“智能拆解”。",
            "ai.status.imported": "AI 任务已加入待办。",

            // AI provider
            "ai.provider": "AI 服务商",
            "ai.baseUrl": "Base URL（OpenAI 兼容）",
            "ai.model": "模型",
            "ai.key": "API Key",
            "ai.keyNoConfig": "未配置 Key，AI 功能将使用本地规划器。",
            "ai.keyConfigured": "已配置 Key，AI 功能将调用所选服务商。",
            "ai.error.requestFailed": "AI 请求失败（%d）：%@",
            "ai.error.empty": "AI 返回内容为空，请重试。",
            "ai.error.noBaseURL": "请填写 Base URL。",
            "ai.error.noModel": "请填写模型名称。",

            // Purchase
            "purchase.fetchFailed": "产品加载失败：%@",
            "purchase.success": "购买成功",
            "purchase.verifyFailed": "购买校验失败",
            "purchase.cancelled": "用户取消支付",
            "purchase.pending": "支付待处理",
            "purchase.failed": "购买失败：%@",
            "purchase.restoreFailed": "恢复失败：%@",

            // Feature gate banner
            "banner.freeDesc": "当前为免费体验，开启订阅可立即解锁。",
            "banner.unlockNow": "立即解锁",

            // Task type
            "taskType.personal": "个人",
            "taskType.code": "代码",
            "taskType.product": "产品",
            "taskType.learning": "学习",
            "taskType.life": "生活",

            // Health labels
            "health.wait": "等待任务输入",
            "health.good": "状态很好",
            "health.forward": "稳步推进",
            "health.context": "补充上下文",
            "health.breakdown": "需要拆解",

            // Companion
            "buddy.settings": "伙伴设置",
            "buddy.name": "伙伴名字",
            "buddy.greeting": "进门问候",
            "buddy.directWrite": "直接读写",
            "buddy.comingSoon": "即将到来",
            "buddy.placeholder": "说点什么…",
            "buddy.noMemory": "（还没说过话）",
            "buddy.silent": "（我沉默了一下，稍等再聊）",
            "buddy.send": "发送",
            "buddy.addTodo": "加入待办",
            "buddy.addedTodo": "已加入待办 ✓",
            "buddy.completed": "已完成 ✓",
            "buddy.splitTask": "拆解后已加入待办 ✓",

            // Notifications
            "notification.dueTitle": "任务到期",
            "notification.dueBody": "「%@」今天到期",
            "noticeTitle": "提醒通知",
            "noticeEnable": "允许提醒",
            "noticeEnabled": "提醒已开启",
            "noticeDenied": "通知被拒绝，点此重新开启",

            // Quota（AI 托管额度）
            "quota.exceeded.free": "免费额度已用完：订阅 Pro 或填自己的 API Key",
            "quota.exceeded.daily": "今日额度已用完，明天恢复",
            "quota.exceeded.other": "额度受限：%@",
            "quota.missingBaseURL": "未配置 AI 额度服务",
            "quota.server": "AI 服务错误（%@ %@）",

            // Voice（伙伴语音输入）
            "voice.micA11y": "语音输入",
            "voice.stopRecording": "结束录音",
            "voice.speechUnavailable": "语音识别暂不可用",
            "voice.micPermissionDenied": "麦克风/语音权限被拒绝，请在系统设置中开启",
            "voice.sessionFailed": "录音会话失败：%@",
            "voice.engineFailed": "录音引擎失败：%@",
        ],
        "en": [
            "tab.today": "Today Plan",
            "tab.tasks": "Tasks",
            "tab.settings": "Settings",
            "tab.companion": "Companion",

            "dashboard.title": "Today Panel",
            "dashboard.subtitle": "AI-native Todo",
            "dashboard.premiumOn": "Premium active",
            "dashboard.freeMode": "Free mode",
            "dashboard.subscribed": "Subscription active",
            "dashboard.trialLeft": "%d days left in trial",
            "dashboard.bannerTitle": "Upgrade for AI Today Plan",
            "dashboard.todayPlan": "Today Plan",
            "dashboard.aiGenerate": "AI Generate",
            "dashboard.aiGenerateA11y": "Generate today's plan with AI",
            "dashboard.regenerate": "Regenerate",
            "dashboard.regenerateA11y": "Regenerate today's plan",
            "dashboard.emptyPlan": "No tasks yet. Add one from the Tasks tab.",
            "dashboard.emptyA11y": "Task list is empty",
            "dashboard.subscribe": "Subscribe",
            "dashboard.execution": "Execution status",
            "dashboard.progress": "Completion %d%% · Health %d",
            "dashboard.statTotal": "All tasks",
            "dashboard.statActive": "Active",
            "dashboard.statCompleted": "Done",
            "dashboard.statHealth": "Health Score",
            "dashboard.aiShort": "AI",

            "tasks.title": "Tasks",
            "tasks.inboxTag": "Natural language inbox",
            "tasks.headline": "Turn scattered thoughts into executable next steps",
            "tasks.inputPlaceholder": "What do you want to move forward today?",
            "tasks.inputA11y": "Task description",
            "tasks.taskType": "Task Type",
            "tasks.capture": "Capture",
            "tasks.captureA11y": "Capture task",
            "tasks.expand": "More options",
            "tasks.collapse": "Hide options",
            "tasks.context": "Context",
            "tasks.acceptance": "Acceptance Criteria",
            "tasks.prompt": "Next prompt",
            "tasks.priority": "Priority %d",
            "tasks.minutes": "%d min",
            "tasks.dueDate": "Due Date",
            "tasks.clearDue": "Clear due date",
            "tasks.listTitle": "Task List",
            "tasks.clearCompleted": "Clear completed",
            "tasks.clearCompletedA11y": "Clear completed tasks",
            "tasks.taskCount": "%d tasks",
            "tasks.type": "Type",
            "tasks.allTypes": "All types",
            "tasks.typeA11y": "Filter by task type",
            "tasks.filterA11y": "Filter: %@",
            "tasks.emptyTitle": "Your task queue is empty",
            "tasks.emptyHint": "Capture one goal first, and I'll turn it into next steps.",
            "tasks.upgrade": "Upgrade",
            "tasks.upgradeA11y": "Upgrade to premium",

            "filter.all": "All",
            "filter.active": "Active",
            "filter.completed": "Completed",
            "filter.high": "High priority",

            "card.start": "Start",
            "card.complete": "Complete",
            "card.done": "Completed",
            "card.archived": "Archived",
            "card.statusTodo": "To do",
            "card.statusDoing": "In progress",
            "card.statusDone": "Done",
            "card.statusArchived": "Archived",
            "card.markDone": "Mark as done",
            "card.unmarkDone": "Undo complete",
            "card.minutes": "%d min",
            "card.updateStatusA11y": "Set status to %@",
            "card.editA11y": "Edit task",
            "card.chipContext": "Context",
            "card.chipAcceptance": "Acceptance",
            "card.chipPrompt": "Next",
            "card.chipSource": "From: %@",
            "card.archive": "Archive",
            "card.delete": "Delete",
            "card.a11y": "Task %@, type %@, priority %d, %@, estimated %d min",

            "settings.account": "Account & Subscription",
            "settings.trial": "Trial",
            "settings.trialDays": "%d days left",
            "settings.trialEnded": "Ended",
            "settings.premium": "Premium",
            "settings.subscribed": "Subscribed",
            "settings.notSubscribed": "Not subscribed",
            "settings.ai": "AI Settings",
            "settings.aiKey": "OpenAI API Key",
            "settings.aiNoKey": "No key configured. AI features will use the local planner.",
            "settings.aiHasKey": "Key configured. AI features will call OpenAI.",
            "settings.obsidian": "Obsidian Export",
            "settings.generateExport": "Generate today's export",
            "settings.fileName": "File name",
            "settings.exportLocked": "Export is a subscription feature",
            "settings.unlockExport": "Subscribe to unlock advanced export",
            "settings.billing": "Billing",
            "settings.restore": "Restore Purchases",
            "settings.benefits": "Premium Benefits",
            "settings.benefitAI": "AI Plan",
            "settings.benefitExport": "Advanced Export",
            "settings.benefitAnalytics": "Analytics Dashboard",
            "settings.status": "Status",
            "settings.shareFile": "Share export file",
            "settings.copied": "Copied",
            "settings.copy": "Copy to clipboard",
            "settings.exportTitle": "Today's Export",
            "settings.language": "语言 / Language",
            "settings.zh": "中文",
            "settings.en": "English",
            "settings.unlockPremium": "Unlock Premium",

            "common.cancel": "Cancel",
            "common.save": "Save",
            "common.done": "Done",

            "edit.title": "Edit Task",
            "edit.titleSection": "Title",
            "edit.titlePlaceholder": "Task title",
            "edit.details": "Details",
            "edit.plan": "Planning",

            "paywall.title": "Unlock Pro Experience",
            "paywall.trialLeft": "You're in your free trial with %d days left.",
            "paywall.trialEnded": "Your trial has ended. Subscribe to keep using premium features.",
            "paywall.perks": "Premium benefits: AI Today Plan, Analytics Dashboard, Advanced Export, task templates, theme packs.",
            "paywall.loading": "Loading...",
            "paywall.noProducts": "No products found. Check StoreKit configuration and retry.",
            "paywall.refresh": "Refresh products",
            "paywall.manage": "To switch or manage your subscription, use App Store subscription settings.",
            "paywall.subscribe": "Subscribe",
            "paywall.close": "Close",

            "ai.title": "AI Workbench",
            "ai.goal": "Goal / Need / Idea",
            "ai.goalA11y": "Goal input",
            "ai.breakdown": "AI Breakdown",
            "ai.summary": "Review / Next step",
            "ai.todayPlan": "Generate Today Plan",
            "ai.output": "AI Output",
            "ai.outputEmpty": "No output yet. Without an API key, the local planner is used; fill in a key to call OpenAI.",
            "ai.addToTodo": "Add to Todo (%d)",

            "ai.status.noGoal": "Enter a goal or idea first.",
            "ai.status.breakdownBusy": "Calling AI to split tasks...",
            "ai.status.breakdownLocal": "Using local planner...",
            "ai.status.saved": "Saved",
            "ai.status.breakdownResult": "Generated %d tasks, ready to add to todo.",
            "ai.status.summaryBusy": "Generating review...",
            "ai.status.summaryLocal": "Using local review generator...",
            "ai.status.summaryDone": "Review generated.",
            "ai.status.planBusy": "Generating today's plan...",
            "ai.status.planLocal": "Using local plan generator...",
            "ai.status.planDone": "Today's plan generated.",
            "ai.status.noImport": "No AI tasks available. Run \"AI Breakdown\" first.",
            "ai.status.imported": "AI tasks added to todo.",

            "ai.provider": "AI Provider",
            "ai.baseUrl": "Base URL (OpenAI compatible)",
            "ai.model": "Model",
            "ai.key": "API Key",
            "ai.keyNoConfig": "No key configured. AI features will use the local planner.",
            "ai.keyConfigured": "Key configured. AI features will call the selected provider.",
            "ai.error.requestFailed": "AI request failed (%d): %@",
            "ai.error.empty": "Empty AI output, please retry.",
            "ai.error.noBaseURL": "Please fill in the Base URL.",
            "ai.error.noModel": "Please fill in the model name.",

            "purchase.fetchFailed": "Product fetch failed: %@",
            "purchase.success": "Purchase successful",
            "purchase.verifyFailed": "Purchase verification failed",
            "purchase.cancelled": "Purchase cancelled",
            "purchase.pending": "Purchase pending",
            "purchase.failed": "Purchase failed: %@",
            "purchase.restoreFailed": "Restore failed: %@",

            "banner.freeDesc": "This is a free preview. Subscribe to unlock instantly.",
            "banner.unlockNow": "Unlock now",

            "taskType.personal": "Personal",
            "taskType.code": "Code",
            "taskType.product": "Product",
            "taskType.learning": "Learning",
            "taskType.life": "Life",

            "health.wait": "Waiting for tasks",
            "health.good": "Great pace",
            "health.forward": "Steady progress",
            "health.context": "Add more context",
            "health.breakdown": "Break down further",

            "buddy.settings": "Companion",
            "buddy.name": "Buddy name",
            "buddy.greeting": "Greeting on launch",
            "buddy.directWrite": "Direct read/write",
            "buddy.comingSoon": "Coming soon",
            "buddy.placeholder": "Say something...",
            "buddy.noMemory": "(No conversations yet)",
            "buddy.silent": "(I went quiet for a moment. Let's talk again soon.)",
            "buddy.send": "Send",
            "buddy.addTodo": "Add to todos",
            "buddy.addedTodo": "Added to todo ✓",
            "buddy.completed": "Marked done ✓",
            "buddy.splitTask": "Split and added to todo ✓",

            "notification.dueTitle": "Task due",
            "notification.dueBody": "\"%@\" is due today",
            "noticeTitle": "Reminders",
            "noticeEnable": "Enable reminders",
            "noticeEnabled": "Reminders enabled",
            "noticeDenied": "Notifications are blocked — tap to re-enable",

            // Quota (managed AI quota)
            "quota.exceeded.free": "Free quota used up: subscribe to Pro or add your own API key",
            "quota.exceeded.daily": "Daily quota used up — try again tomorrow",
            "quota.exceeded.other": "Quota limited: %@",
            "quota.missingBaseURL": "AI quota service not configured",
            "quota.server": "AI service error (%@ %@)",

            // Voice (companion voice input)
            "voice.micA11y": "Voice input",
            "voice.stopRecording": "Stop recording",
            "voice.speechUnavailable": "Speech recognition unavailable",
            "voice.micPermissionDenied": "Microphone/speech permission denied — enable it in Settings",
            "voice.sessionFailed": "Recording session failed: %@",
            "voice.engineFailed": "Recording engine failed: %@",
        ],
    ]

    static func t(_ key: String) -> String {
        let lang = currentLanguage
        return table[lang]?[key] ?? table["zh"]?[key] ?? key
    }

    static func t(_ key: String, _ args: CVarArg...) -> String {
        let value = t(key)
        return String(format: value, arguments: args)
    }

    static var currentLanguage: String {
        UserDefaults.standard.string(forKey: languageKey) ?? "zh"
    }

    static func setLanguage(_ language: String) {
        UserDefaults.standard.set(language, forKey: languageKey)
    }
}
