import Foundation

enum Localization {
    static let languageKey = "app_language"

    private static let table: [String: [String: String]] = [
        "zh": [
            // Tabs
            "tab.today": "今日计划",
            "tab.tasks": "任务",
            "tab.settings": "设置",
            "tab.companion": "伙伴",

            // Dashboard
            "dashboard.title": "今日",
            "dashboard.subtitle": "AI-native Todo",
            "dashboard.premiumOn": "高级已开启",
            "dashboard.freeMode": "免费模式",
            "dashboard.subscribed": "订阅有效",
            "dashboard.trialLeft": "试用剩余 %d 天",
            "dashboard.bannerTitle": "AI 今日计划可升级",
            "dashboard.todayPlan": "今日计划",
            "dashboard.aiGenerate": "AI 生成",
            "dashboard.aiGenerateA11y": "AI 生成今日计划",
            "dashboard.regenerate": "重新生成",
            "dashboard.regenerateA11y": "重新生成今日计划",
            "dashboard.emptyPlan": "今天还没有任务，先去任务页添加一条吧。",
            "dashboard.emptyA11y": "任务列表为空",
            "dashboard.subscribe": "订阅",
            "dashboard.execution": "执行态势",
            "dashboard.progress": "完成率 %d%% · 健康分 %d",
            "dashboard.statTotal": "全部任务",
            "dashboard.statActive": "进行中",
            "dashboard.statCompleted": "已完成",
            "dashboard.statHealth": "健康分",
            "dashboard.aiShort": "AI",
            "dashboard.aiOptimize": "AI 优化",

            // Tasks
            "tasks.title": "任务",
            "tasks.inboxTag": "Natural language inbox",
            "tasks.headline": "把脑内噪音变成可执行下一步",
            "tasks.inputPlaceholder": "今天想推进什么？",
            "tasks.inputA11y": "任务描述",
            "tasks.taskType": "任务类型",
            "tasks.capture": "捕捉",
            "tasks.captureA11y": "捕捉任务",
            "tasks.expand": "展开高级选项",
            "tasks.collapse": "收起高级选项",
            "tasks.context": "上下文",
            "tasks.acceptance": "验收标准",
            "tasks.prompt": "下一步 Prompt",
            "tasks.priority": "优先级 %d",
            "tasks.minutes": "%d 分钟",
            "tasks.dueDate": "截止日期",
            "tasks.clearDue": "清除截止日期",
            "tasks.listTitle": "任务列表",
            "tasks.clearCompleted": "清除已完成",
            "tasks.clearCompletedA11y": "清除已完成任务",
            "tasks.taskCount": "%d 个任务",
            "tasks.type": "类型",
            "tasks.allTypes": "全部类型",
            "tasks.typeA11y": "按任务类型筛选",
            "tasks.filterA11y": "筛选：%@",
            "tasks.emptyTitle": "任务队列还是空的",
            "tasks.emptyHint": "先捕捉一个目标，我会帮你压成下一步。",
            "tasks.upgrade": "升级",
            "tasks.upgradeA11y": "升级高级功能",

            // Filter
            "filter.all": "全部",
            "filter.active": "进行中",
            "filter.completed": "已完成",
            "filter.high": "高优先级",

            // Task card
            "card.start": "开始",
            "card.complete": "完成",
            "card.done": "已完成",
            "card.archived": "已归档",
            "card.statusTodo": "待开始",
            "card.statusDoing": "进行中",
            "card.statusDone": "已完成",
            "card.statusArchived": "已归档",
            "card.markDone": "标记完成",
            "card.unmarkDone": "取消完成",
            "card.minutes": "%d 分钟",
            "card.updateStatusA11y": "更新状态为%@",
            "card.editA11y": "编辑任务",
            "card.chipContext": "上下文",
            "card.chipAcceptance": "验收标准",
            "card.chipPrompt": "下一步",
            "card.chipSource": "源自：%@",
            "card.archive": "归档",
            "card.delete": "删除",
            "card.a11y": "任务%@，类型%@，优先级%d，%@，估算%d分钟",

            // Settings
            "settings.account": "账号与订阅",
            "settings.testNotification": "发送测试通知",
            "settings.testBody": "这是提醒测试通知",
            "settings.testSent": "已调度，5 秒后应收到",
            "settings.testDenied": "调度失败：通知权限被拒或系统受限",
            "settings.testFailed": "通知测试失败",
            "settings.pendingCount": "%d 条待发提醒",
            "settings.trial": "试用",
            "settings.trialDays": "剩余 %d 天",
            "settings.trialEnded": "已结束",
            "settings.premium": "高级",
            "settings.subscribed": "已订阅",
            "settings.notSubscribed": "未订阅",
            "settings.ai": "AI 设置",
            "settings.aiKey": "OpenAI API Key",
            "settings.aiNoKey": "未配置 Key，AI 功能将使用本地规划器。",
            "settings.aiHasKey": "已配置 Key，AI 功能将调用 OpenAI。",
            "settings.obsidian": "Obsidian 导出",
            "settings.generateExport": "生成今日导出",
            "settings.fileName": "文件名",
            "settings.exportLocked": "导出为订阅功能",
            "settings.unlockExport": "订阅解锁高级导出",
            "settings.billing": "账务",
            "settings.restore": "恢复购买",
            "settings.manageSubscriptions": "管理订阅",
            "settings.benefits": "高级权益",
            "settings.benefitAI": "AI 计划",
            "settings.benefitExport": "高级导出",
            "settings.benefitAnalytics": "分析看板",
            "settings.status": "状态",
            "settings.shareFile": "分享导出文件",
            "settings.copied": "已复制",
            "settings.copy": "复制到剪贴板",
            "settings.exportTitle": "今日导出",
            "settings.language": "语言 / Language",
            "settings.zh": "中文",
            "settings.en": "English",
            "settings.unlockPremium": "解锁订阅",
            "settings.privacy": "隐私政策",
            "settings.terms": "使用条款",
            "settings.support": "支持",
            "settings.supportID": "支持 ID",
            "settings.supportIDDetail": "联系支持申请删除托管服务记录时，请提供此匿名 ID。不要在公开截图中分享。",
            "settings.copySupportID": "复制支持 ID",
            "settings.supportIDCopied": "支持 ID 已复制",
            "settings.copySupportIDA11yHint": "复制匿名支持 ID，以便在私密支持请求中提供。",
            "settings.aiConsentRevoke": "撤回远程 AI 授权",
            "settings.aiConsentRevokeTitle": "撤回远程 AI 授权？",
            "settings.aiConsentRevokeDetail": "撤回后，下一次远程 AI 请求会再次征求授权；本地规划器仍可使用。",
            "settings.deleteAIConfiguration": "删除本地 AI 配置",
            "settings.deleteAIConfigurationTitle": "删除本地 AI 配置？",
            "settings.deleteAIConfigurationDetail": "这会删除钥匙串中的 API Key、提供商/模型/Base URL 设置和本机授权记录。不会删除远端额度、订阅记录或 AI 提供商保存的数据。",
            "settings.deleteAIConfigurationConfirm": "删除本地配置",
            "settings.deleteAIConfigurationErrorTitle": "无法删除本地 AI 配置",
            "settings.deleteAIConfigurationErrorDetail": "钥匙串操作失败，本地 AI 配置可能仍被保留。请稍后重试。",

            // Remote AI consent
            "ai.consent.title": "远程 AI 数据授权",
            "ai.consent.summary": "只有你明确同意后，相同授权版本和接收方的远程 AI 请求才会发送。",
            "ai.consent.transmittedTitle": "将发送的内容",
            "ai.consent.transmittedContent": "你的目标、任务标题、状态、优先级、截止时间与上下文，健康分，伙伴聊天、记忆摘要、活动事件，以及生成结果所需的提示上下文。语音发送给 AI 接收方前会先转成文字，原始录音不会发送给该 AI 接收方。",
            "ai.consent.recipientTitle": "接收方",
            "ai.consent.recipient": "%@",
            "ai.consent.managedRecipient": "托管 AI 服务（%@）与 DeepSeek",
            "ai.consent.managedRouteDetail": "内容和用于额度控制的随机设备标识会先发送到托管 AI 服务，再由其转发给 DeepSeek。",
            "ai.consent.byokRouteDetail": "内容会使用你保存在钥匙串中的 API Key，直接发送到所选 AI 提供商，不经过托管 AI 服务。",
            "ai.consent.declineDetail": "选择暂不使用后不会发送这些内容；本地规划器仍可使用。",
            "ai.consent.revokeDetail": "你可以随时在“设置”中撤回授权。接收方或授权版本变化时，应用会再次询问。",
            "ai.consent.privacy": "查看隐私政策",
            "ai.consent.decline": "暂不使用远程 AI",
            "ai.consent.continue": "同意并继续",

            // Common
            "common.cancel": "取消",
            "common.ok": "好",
            "common.save": "保存",
            "common.done": "完成",

            // Edit
            "edit.title": "编辑任务",
            "edit.titleSection": "标题",
            "edit.titlePlaceholder": "任务标题",
            "edit.details": "详情",
            "edit.plan": "规划",

            // Paywall
            "paywall.title": "解锁专业体验",
            "paywall.trialLeft": "你现在在免费试用期，剩余 %d 天。",
            "paywall.trialEnded": "试用已结束，请订阅以继续使用高级功能。",
            "paywall.localTrialDisclosure": "此 7 天体验仅保存在本机，不是 App Store 订阅的首购优惠。",
            "paywall.perks": "高级权限：AI 今日计划、分析看板、高级导出，一次订阅全部解锁。",
            "paywall.loading": "加载中…",
            "paywall.noProducts": "暂未读取到商品信息，请检查 StoreKit 配置后重试。",
            "paywall.refresh": "刷新商品",
            "paywall.manage": "如需切换/管理订阅，可在 App Store 的订阅设置中完成。",
            "paywall.subscribe": "订阅",
            "paywall.close": "关闭",
            "paywall.pricePerPeriod": "%@ / %@",
            "paywall.purchaseAccessibility": "购买%@，%@每%@",
            "paywall.period.day": "天",
            "paywall.period.days": "%d 天",
            "paywall.period.week": "周",
            "paywall.period.weeks": "%d 周",
            "paywall.period.month": "月",
            "paywall.period.months": "%d 个月",
            "paywall.period.year": "年",
            "paywall.period.years": "%d 年",
            "paywall.introFreeTrial": "符合条件时，首购优惠为免费 %@",
            "paywall.introPrice": "符合条件时，首购优惠为 %@ / %@",
            "paywall.introPayAsYouGo": "符合条件时，首购优惠为 %@ / %@，共 %@",
            "paywall.introPayUpFront": "符合条件时，首购优惠为预付 %@，覆盖 %@",
            "paywall.autoRenewDisclosure": "订阅会按所示价格和周期自动续订，除非在当前周期结束至少 24 小时前取消。",
            "paywall.cancellationDisclosure": "购买后可在 App Store 的“订阅”中管理或取消。",

            // AI workbench
            "ai.title": "AI 工作台",
            "ai.goal": "目标 / 需求 / 想法",
            "ai.goalA11y": "目标输入",
            "ai.breakdown": "智能拆解",
            "ai.summary": "复盘与下一步",
            "ai.todayPlan": "生成今日计划",
            "ai.output": "AI 输出",
            "ai.outputEmpty": "还没有内容。没有 API Key 时会使用本地规划器；填入 Key 后会调用 OpenAI。",
            "ai.addToTodo": "加入待办 (%d)",
            "ai.brief.title": "今日 AI 简报",
            "ai.brief.toolbar": "AI 简报",
            "ai.brief.updatedAt": "今天 %@ 更新",
            "ai.brief.updateAvailable": "建议可更新",
            "ai.brief.local": "本地建议",
            "ai.brief.refresh": "更新简报",
            "ai.brief.refreshing": "正在更新简报",
            "ai.brief.loading": "正在生成今日简报",
            "ai.brief.loadingDetail": "正在结合任务、截止时间与健康分整理今天的重点。",
            "ai.brief.emptyTitle": "今天的简报还未生成",
            "ai.brief.emptyDetail": "点按可先进入 AI 计划助手，也可以在这里更新简报。",
            "ai.brief.open": "打开 AI 简报",
            "ai.brief.openHint": "打开 AI 计划助手",
            "ai.brief.error": "AI 简报提示",
            "ai.brief.manageSubscription": "查看订阅",
            "ai.brief.configureProvider": "配置自己的 API Key",
            "ai.brief.generatePlan": "生成计划",
            "ai.brief.helpPrioritize": "帮我取舍",
            "ai.brief.breakdown": "拆解目标",
            "ai.brief.planPrefill": "请根据今天的任务生成一份可执行计划。",
            "ai.brief.prioritizePrefill": "请帮我取舍今天的任务，说明最该优先做什么。",
            "ai.brief.breakdownPrefill": "请把我今天最重要的目标拆成可执行的小步骤。",
            "ai.brief.localPriority": "先完成「%@」，再安排低耗能任务。",
            "ai.brief.emptySummary": "当前没有待推进任务，留出时间整理与复盘。",
            "ai.brief.steadyDetail": "当前没有 24 小时内到期的任务，可按优先级稳定推进。",
            "ai.brief.deadlineDetail": "有 %d 项任务将在 24 小时内到期，优先保护交付。",
            "ai.brief.activeEvidence": "进行中任务 %d 项",
            "ai.brief.deadlineEvidence": "24 小时内到期 %d 项",
            "ai.brief.healthEvidence": "当前健康分 %d",
            "ai.workbench.title": "AI 计划助手",
            "ai.workbench.subtitle": "把想法变成下一步",
            "ai.workbench.service": "AI 服务",
            "ai.workbench.service.custom": "自带 Key",
            "ai.workbench.service.managed": "托管 AI",
            "ai.workbench.service.local": "本地规划器",
            "ai.workbench.result.local": "本次结果 · 本地",
            "ai.workbench.status.configured": "已配置",
            "ai.workbench.status.managedQuota": "托管额度",
            "ai.workbench.status.remoteSuccess": "本次远端生成成功",
            "ai.workbench.status.localFallback": "本次使用本地建议",
            "ai.workbench.status.quotaExceeded": "托管额度已用完",
            "ai.workbench.status.remaining": "托管额度剩余 %d/%d 次。",
            "ai.workbench.mode": "工作模式",
            "ai.workbench.todayPlan": "今日计划",
            "ai.workbench.breakdown": "拆解目标",
            "ai.workbench.review": "复盘",
            "ai.workbench.context": "任务上下文",
            "ai.workbench.contextSummary": "已读取 %d 项任务、%d 个截止时间与当前健康分 %d。",
            "ai.workbench.contextDetail": "待开始 %d 项 · 进行中 %d 项 · 已完成 %d 项",
            "ai.workbench.noAutomaticChanges": "只生成建议；不会自动修改、删除或重排任务。",
            "ai.workbench.todayPlanQuestion": "今天最值得推进什么？",
            "ai.workbench.breakdownQuestion": "你想把哪个目标拆成下一步？",
            "ai.workbench.reviewQuestion": "这次复盘最需要看清什么？",
            "ai.workbench.todayPlanPlaceholder": "可补充今天的时间、精力或必须完成的事项",
            "ai.workbench.breakdownPlaceholder": "输入目标、背景和你希望达到的结果",
            "ai.workbench.reviewPlaceholder": "可补充进展、阻塞或需要取舍的问题",
            "ai.workbench.todayPlanChip.focus": "只排 3 件事",
            "ai.workbench.todayPlanChip.buffer": "保留缓冲时间",
            "ai.workbench.todayPlanChip.deadlines": "优先临近截止",
            "ai.workbench.breakdownChip.smallSteps": "拆成 30 分钟步骤",
            "ai.workbench.breakdownChip.risks": "标出约束和风险",
            "ai.workbench.breakdownChip.verify": "每步都可验证",
            "ai.workbench.reviewChip.progress": "总结已完成进展",
            "ai.workbench.reviewChip.blockers": "找出主要阻塞",
            "ai.workbench.reviewChip.next": "只给一个下一步",
            "ai.workbench.goalA11y": "AI 计划目标与补充要求",
            "ai.workbench.generatePlan": "生成今日建议",
            "ai.workbench.generateBreakdown": "智能拆解",
            "ai.workbench.generateReview": "生成复盘",
            "ai.workbench.loading": "正在生成建议",
            "ai.workbench.loadingDetail": "正在结合当前任务、截止时间和健康分整理结果。",
            "ai.workbench.result": "AI 建议",
            "ai.workbench.result.retained": "保留上次结果",
            "ai.workbench.result.stale": "输入已变化 · 上次结果",
            "ai.workbench.resultReady": "AI 建议已生成。",
            "ai.workbench.emptyResult": "当前没有可展示的建议，可补充要求后重新生成。",
            "ai.workbench.error": "生成失败",
            "ai.workbench.retry": "重试",
            "ai.workbench.regenerate": "重新生成",
            "ai.workbench.addToToday": "加入今日计划（%d）",
            "ai.workbench.addToTodo": "加入待办（%d）",
            "ai.workbench.appliedToToday": "已将 %d 项安排到今日计划。",
            "ai.workbench.imported": "已导入 %d 条 AI 建议。",
            "ai.workbench.confirmation.today": "已更新今日计划（%d 项）。",
            "ai.workbench.confirmation.tasks": "已加入待办（%d 项）。",
            "ai.workbench.selected": "已选择",
            "ai.workbench.notSelected": "未选择",
            "ai.workbench.minutes": "%d 分钟",
            "ai.workbench.priority": "优先级 %d",
            "ai.workbench.dueDate": "截止 %@",
            "ai.workbench.existingTaskReason": "基于现有任务的优先级与截止时间。",
            "ai.workbench.localPlanOverview": "先聚焦最重要的任务，并为变化保留余量。",
            "ai.workbench.defaultGoal": "当前目标",
            "ai.workbench.defineDone": "明确「%@」的完成标准",
            "ai.workbench.collectContext": "收集现有资料、约束与风险",
            "ai.workbench.buildMinimum": "完成一个可验证的最小版本",
            "ai.workbench.verifyResult": "验证结果并记录下一步",
            "ai.workbench.localReason": "本地规划器生成的可执行步骤。",
            "ai.workbench.localBreakdownOverview": "先把目标压缩成可验证的小步骤。",
            "ai.workbench.localReviewOverview": "基于当前任务状态生成本地复盘。",
            "ai.workbench.progress": "进展概览",
            "ai.workbench.progressBody": "已完成 %d 项未归档任务。",
            "ai.workbench.next": "下一步建议",
            "ai.workbench.nextBody": "选择一个最高优先级任务，定义完成标准后推进。",
            "ai.workbench.nextPrompt": "推荐给 AI 的提示",
            "ai.workbench.nextPromptBody": "请根据我当前的任务，找出最值得优先推进的一步，并说明取舍。",

            // AI status
            "ai.status.noGoal": "先输入一个目标或想法。",
            "ai.status.breakdownBusy": "正在调用 AI 拆解...",
            "ai.status.breakdownLocal": "使用本地规划器拆解...",
            "ai.status.saved": "已保存",
            "ai.status.breakdownResult": "已生成 %d 条任务，可一键加入待办。",
            "ai.status.summaryBusy": "正在生成复盘...",
            "ai.status.summaryLocal": "使用本地状态生成复盘...",
            "ai.status.summaryDone": "复盘已生成。",
            "ai.status.planBusy": "正在生成今日计划...",
            "ai.status.planLocal": "使用本地队列生成今日计划...",
            "ai.status.planDone": "今日计划已生成。",
            "ai.status.noImport": "当前没有可导入的 AI 任务。请先执行“智能拆解”。",
            "ai.status.imported": "AI 任务已加入待办。",

            // AI provider
            "ai.provider": "AI 服务商",
            "ai.baseUrl": "Base URL（OpenAI 兼容）",
            "ai.model": "模型",
            "ai.model.custom": "自定义模型",
            "ai.managedFixedModel": "未配置 API Key，托管额度固定使用 DeepSeek V4 Flash。",
            "ai.modelSelectorHint": "从当前服务商的常用模型中选择，也可使用自定义模型。",
            "ai.customModelPlaceholder": "输入自定义模型 ID",
            "ai.customBaseURLHint": "自定义服务商需填写 OpenAI 兼容的 Base URL。",
            "ai.key": "API Key",
            "ai.keyNoConfig": "未配置 Key，AI 功能将使用本地规划器。",
            "ai.keyConfigured": "已配置 Key，AI 功能将调用所选服务商。",
            "ai.keySaveFailed": "API Key 未能保存到钥匙串，已恢复之前的值。",
            "ai.error.requestFailed": "AI 请求失败（%d）：%@",
            "ai.error.empty": "AI 返回内容为空，请重试。",
            "ai.error.noBaseURL": "请填写 Base URL。",
            "ai.error.noModel": "请填写模型名称。",

            // Purchase
            "purchase.fetchFailed": "产品加载失败：%@",
            "purchase.success": "购买成功",
            "purchase.verifyFailed": "购买校验失败",
            "purchase.cancelled": "用户取消支付",
            "purchase.pending": "支付待处理",
            "purchase.failed": "购买失败：%@",
            "purchase.restoreFailed": "恢复失败：%@",
            "purchase.registrationUnavailable": "Apple 订阅已生效；托管 AI 服务尚未配置，将在下次权益刷新时重试。",
            "purchase.registrationRetry": "Apple 订阅仍然有效；托管 AI 权益同步失败，将在下次权益刷新时重试。",
            "purchase.refreshRegistration": "刷新权益并重试",

            // Feature gate banner
            "banner.freeDesc": "当前为免费体验，开启订阅可立即解锁。",
            "banner.unlockNow": "立即解锁",

            // Task type
            "taskType.personal": "个人",
            "taskType.code": "代码",
            "taskType.product": "产品",
            "taskType.learning": "学习",
            "taskType.life": "生活",

            // Health labels
            "health.wait": "等待任务输入",
            "health.good": "状态很好",
            "health.forward": "稳步推进",
            "health.context": "补充上下文",
            "health.breakdown": "需要拆解",

            // Companion
            "buddy.settings": "伙伴设置",
            "buddy.name": "伙伴名字",
            "buddy.greeting": "进门问候",
            "buddy.directWrite": "直接读写",
            "buddy.comingSoon": "即将到来",
            "buddy.placeholder": "说点什么…",
            "buddy.noMemory": "（还没说过话）",
            "buddy.silent": "（我沉默了一下，稍等再聊）",
            "buddy.send": "发送",
            "buddy.addTodo": "加入待办",
            "buddy.addedTodo": "已加入待办 ✓",
            "buddy.completed": "已完成 ✓",
            "buddy.splitTask": "拆解后已加入待办 ✓",

            // Notifications
            "notification.dueTitle": "任务到期",
            "notification.dueBody": "「%@」今天到期",
            "noticeTitle": "提醒通知",
            "noticeEnable": "允许提醒",
            "noticeEnabled": "提醒已开启",
            "noticeDenied": "通知被拒绝，点此重新开启",
            "notice.systemStatus": "系统权限",
            "notice.systemAllowed": "已允许",
            "notice.systemDenied": "未允许通知",
            "notice.systemNotDetermined": "尚未请求",
            "notice.openSettings": "打开系统设置",
            "notice.permissionExplanation": "开启后，只有设置了到期时间的未完成任务会发送提醒。关闭会移除待发任务提醒。",
            "notice.debugPendingCount": "%d 条任务提醒待发送（调试）",

            // Quota（AI 托管额度）
            "quota.exceeded.free": "免费额度已用完：订阅 Pro 或填自己的 API Key",
            "quota.exceeded.daily": "今日额度已用完，明天恢复",
            "quota.exceeded.other": "额度受限：%@",
            "quota.missingBaseURL": "未配置 AI 额度服务",
            "quota.server": "AI 服务错误（%d %@）",

            // Voice（伙伴语音输入）
            "voice.micA11y": "语音输入",
            "voice.stopRecording": "结束录音",
            "voice.speechUnavailable": "语音识别暂不可用",
            "voice.micPermissionDenied": "麦克风/语音权限被拒绝，请在系统设置中开启",
            "voice.sessionFailed": "录音会话失败：%@",
            "voice.engineFailed": "录音引擎失败：%@",
            "voice.errorTitle": "语音输入不可用",
            "voice.switchToVoice": "切换到语音输入",
            "voice.switchToKeyboard": "切换到键盘输入",
            "voice.cancelAndSwitchToKeyboard": "取消语音并切换到键盘",
            "voice.startRecording": "点击开始说话",
            "voice.requestingPermission": "正在请求语音权限…",
            "voice.recording": "正在聆听，点击结束",
            "voice.finalizing": "正在整理语音…",
            "voice.openSettings": "打开系统设置",
            "voice.speechPermissionDenied": "语音识别权限被拒绝，请在系统设置中开启。",
            "voice.microphonePermissionDenied": "麦克风权限被拒绝，请在系统设置中开启。",
            "voice.recognitionFailed": "语音识别失败，请重试。",
            "voice.noSpeechDetected": "没有听清内容，请再试一次。",
            "voice.transcriptReady": "语音已加入输入框，确认后再发送。",
        ],
        "en": [
            "tab.today": "Today Plan",
            "tab.tasks": "Tasks",
            "tab.settings": "Settings",
            "tab.companion": "Companion",

            "dashboard.title": "Today",
            "dashboard.subtitle": "AI-native Todo",
            "dashboard.premiumOn": "Premium active",
            "dashboard.freeMode": "Free mode",
            "dashboard.subscribed": "Subscription active",
            "dashboard.trialLeft": "%d days left in trial",
            "dashboard.bannerTitle": "Upgrade for AI Today Plan",
            "dashboard.todayPlan": "Today Plan",
            "dashboard.aiGenerate": "AI Generate",
            "dashboard.aiGenerateA11y": "Generate today's plan with AI",
            "dashboard.regenerate": "Regenerate",
            "dashboard.regenerateA11y": "Regenerate today's plan",
            "dashboard.emptyPlan": "No tasks yet. Add one from the Tasks tab.",
            "dashboard.emptyA11y": "Task list is empty",
            "dashboard.subscribe": "Subscribe",
            "dashboard.execution": "Execution status",
            "dashboard.progress": "Completion %d%% · Health %d",
            "dashboard.statTotal": "All tasks",
            "dashboard.statActive": "Active",
            "dashboard.statCompleted": "Done",
            "dashboard.statHealth": "Health Score",
            "dashboard.aiShort": "AI",
            "dashboard.aiOptimize": "Optimize with AI",

            "tasks.title": "Tasks",
            "tasks.inboxTag": "Natural language inbox",
            "tasks.headline": "Turn scattered thoughts into executable next steps",
            "tasks.inputPlaceholder": "What do you want to move forward today?",
            "tasks.inputA11y": "Task description",
            "tasks.taskType": "Task Type",
            "tasks.capture": "Capture",
            "tasks.captureA11y": "Capture task",
            "tasks.expand": "More options",
            "tasks.collapse": "Hide options",
            "tasks.context": "Context",
            "tasks.acceptance": "Acceptance Criteria",
            "tasks.prompt": "Next prompt",
            "tasks.priority": "Priority %d",
            "tasks.minutes": "%d min",
            "tasks.dueDate": "Due Date",
            "tasks.clearDue": "Clear due date",
            "tasks.listTitle": "Task List",
            "tasks.clearCompleted": "Clear completed",
            "tasks.clearCompletedA11y": "Clear completed tasks",
            "tasks.taskCount": "%d tasks",
            "tasks.type": "Type",
            "tasks.allTypes": "All types",
            "tasks.typeA11y": "Filter by task type",
            "tasks.filterA11y": "Filter: %@",
            "tasks.emptyTitle": "Your task queue is empty",
            "tasks.emptyHint": "Capture one goal first, and I'll turn it into next steps.",
            "tasks.upgrade": "Upgrade",
            "tasks.upgradeA11y": "Upgrade to premium",

            "filter.all": "All",
            "filter.active": "Active",
            "filter.completed": "Completed",
            "filter.high": "High priority",

            "card.start": "Start",
            "card.complete": "Complete",
            "card.done": "Completed",
            "card.archived": "Archived",
            "card.statusTodo": "To do",
            "card.statusDoing": "In progress",
            "card.statusDone": "Done",
            "card.statusArchived": "Archived",
            "card.markDone": "Mark as done",
            "card.unmarkDone": "Undo complete",
            "card.minutes": "%d min",
            "card.updateStatusA11y": "Set status to %@",
            "card.editA11y": "Edit task",
            "card.chipContext": "Context",
            "card.chipAcceptance": "Acceptance",
            "card.chipPrompt": "Next",
            "card.chipSource": "From: %@",
            "card.archive": "Archive",
            "card.delete": "Delete",
            "card.a11y": "Task %@, type %@, priority %d, %@, estimated %d min",

            "settings.account": "Account & Subscription",
            "settings.testNotification": "Send test notification",
            "settings.testBody": "This is a reminder test",
            "settings.testSent": "Scheduled — you should get it in 5 seconds",
            "settings.testDenied": "Scheduling failed: notifications denied or restricted",
            "settings.testFailed": "Notification test failed",
            "settings.pendingCount": "%d pending reminders",
            "settings.trial": "Trial",
            "settings.trialDays": "%d days left",
            "settings.trialEnded": "Ended",
            "settings.premium": "Premium",
            "settings.subscribed": "Subscribed",
            "settings.notSubscribed": "Not subscribed",
            "settings.ai": "AI Settings",
            "settings.aiKey": "OpenAI API Key",
            "settings.aiNoKey": "No key configured. AI features will use the local planner.",
            "settings.aiHasKey": "Key configured. AI features will call OpenAI.",
            "settings.obsidian": "Obsidian Export",
            "settings.generateExport": "Generate today's export",
            "settings.fileName": "File name",
            "settings.exportLocked": "Export is a subscription feature",
            "settings.unlockExport": "Subscribe to unlock advanced export",
            "settings.billing": "Billing",
            "settings.restore": "Restore Purchases",
            "settings.manageSubscriptions": "Manage Subscriptions",
            "settings.benefits": "Premium Benefits",
            "settings.benefitAI": "AI Plan",
            "settings.benefitExport": "Advanced Export",
            "settings.benefitAnalytics": "Analytics Dashboard",
            "settings.status": "Status",
            "settings.shareFile": "Share export file",
            "settings.copied": "Copied",
            "settings.copy": "Copy to clipboard",
            "settings.exportTitle": "Today's Export",
            "settings.language": "语言 / Language",
            "settings.zh": "中文",
            "settings.en": "English",
            "settings.unlockPremium": "Unlock Premium",
            "settings.privacy": "Privacy Policy",
            "settings.terms": "Terms of Use",
            "settings.support": "Support",
            "settings.supportID": "Support ID",
            "settings.supportIDDetail": "Include this anonymous ID in a private support request to delete managed-service records. Do not share it in public screenshots.",
            "settings.copySupportID": "Copy Support ID",
            "settings.supportIDCopied": "Support ID Copied",
            "settings.copySupportIDA11yHint": "Copies the anonymous Support ID for a private support request.",
            "settings.aiConsentRevoke": "Revoke Remote AI Consent",
            "settings.aiConsentRevokeTitle": "Revoke remote AI consent?",
            "settings.aiConsentRevokeDetail": "The next remote AI request will ask again. The local planner remains available.",
            "settings.deleteAIConfiguration": "Delete Local AI Configuration",
            "settings.deleteAIConfigurationTitle": "Delete local AI configuration?",
            "settings.deleteAIConfigurationDetail": "This deletes the API key from Keychain, provider/model/Base URL settings, and the consent record on this device. It does not delete remote quota, subscription records, or data retained by an AI provider.",
            "settings.deleteAIConfigurationConfirm": "Delete Local Configuration",
            "settings.deleteAIConfigurationErrorTitle": "Could Not Delete Local AI Configuration",
            "settings.deleteAIConfigurationErrorDetail": "The Keychain operation failed, so local AI configuration may remain. Please try again.",

            // Remote AI consent
            "ai.consent.title": "Remote AI Data Consent",
            "ai.consent.summary": "Remote AI requests are sent only after you explicitly agree for the current consent version and recipient.",
            "ai.consent.transmittedTitle": "Content sent",
            "ai.consent.transmittedContent": "Your goal; task titles, status, priority, deadlines, and context; health score; companion chat, memory summary, activity events; and prompt context needed to generate a result. Voice is converted to text before it is sent to the AI recipient; raw recordings are not sent to that AI recipient.",
            "ai.consent.recipientTitle": "Recipient",
            "ai.consent.recipient": "%@",
            "ai.consent.managedRecipient": "Managed AI service (%@) and DeepSeek",
            "ai.consent.managedRouteDetail": "Content and a random device identifier used for quota control go to the managed AI service, which forwards the content to DeepSeek.",
            "ai.consent.byokRouteDetail": "Content goes directly to the selected AI provider using the API key saved in Keychain. It does not pass through the managed AI service.",
            "ai.consent.declineDetail": "If you decline, this content is not sent and the local planner remains available.",
            "ai.consent.revokeDetail": "You can revoke consent in Settings at any time. The app asks again if the recipient or consent version changes.",
            "ai.consent.privacy": "View Privacy Policy",
            "ai.consent.decline": "Not Now — Use Local AI",
            "ai.consent.continue": "Agree and Continue",

            "common.cancel": "Cancel",
            "common.ok": "OK",
            "common.save": "Save",
            "common.done": "Done",

            "edit.title": "Edit Task",
            "edit.titleSection": "Title",
            "edit.titlePlaceholder": "Task title",
            "edit.details": "Details",
            "edit.plan": "Planning",

            "paywall.title": "Unlock Pro Experience",
            "paywall.trialLeft": "You're in your free trial with %d days left.",
            "paywall.trialEnded": "Your trial has ended. Subscribe to keep using premium features.",
            "paywall.localTrialDisclosure": "This seven-day experience is stored on this device. It is not an App Store introductory offer.",
            "paywall.perks": "Premium benefits: AI Today Plan, Analytics Dashboard, and Advanced Export.",
            "paywall.loading": "Loading...",
            "paywall.noProducts": "No products found. Check StoreKit configuration and retry.",
            "paywall.refresh": "Refresh products",
            "paywall.manage": "To switch or manage your subscription, use App Store subscription settings.",
            "paywall.subscribe": "Subscribe",
            "paywall.close": "Close",
            "paywall.pricePerPeriod": "%@ / %@",
            "paywall.purchaseAccessibility": "Purchase %@ for %@ per %@",
            "paywall.period.day": "day",
            "paywall.period.days": "%d days",
            "paywall.period.week": "week",
            "paywall.period.weeks": "%d weeks",
            "paywall.period.month": "month",
            "paywall.period.months": "%d months",
            "paywall.period.year": "year",
            "paywall.period.years": "%d years",
            "paywall.introFreeTrial": "If eligible, introductory offer: %@ free",
            "paywall.introPrice": "If eligible, introductory offer: %@ for %@",
            "paywall.introPayAsYouGo": "If eligible, introductory offer: %@ / %@ for %@",
            "paywall.introPayUpFront": "If eligible, introductory offer: %@ up front for %@",
            "paywall.autoRenewDisclosure": "Subscriptions renew automatically at the shown price and period unless canceled at least 24 hours before the current period ends.",
            "paywall.cancellationDisclosure": "Manage or cancel after purchase in App Store Subscriptions.",

            "ai.title": "AI Workbench",
            "ai.goal": "Goal / Need / Idea",
            "ai.goalA11y": "Goal input",
            "ai.breakdown": "AI Breakdown",
            "ai.summary": "Review / Next step",
            "ai.todayPlan": "Generate Today Plan",
            "ai.output": "AI Output",
            "ai.outputEmpty": "No output yet. Without an API key, the local planner is used; fill in a key to call OpenAI.",
            "ai.addToTodo": "Add to Todo (%d)",
            "ai.brief.title": "Today's AI Brief",
            "ai.brief.toolbar": "AI Brief",
            "ai.brief.updatedAt": "Updated today at %@",
            "ai.brief.updateAvailable": "Update available",
            "ai.brief.local": "On-device suggestion",
            "ai.brief.refresh": "Refresh brief",
            "ai.brief.refreshing": "Refreshing brief",
            "ai.brief.loading": "Creating today's brief",
            "ai.brief.loadingDetail": "Reviewing tasks, deadlines, and your health score to find today's focus.",
            "ai.brief.emptyTitle": "Today's brief is not ready yet",
            "ai.brief.emptyDetail": "Open the AI planning assistant now, or refresh the brief here.",
            "ai.brief.open": "Open AI brief",
            "ai.brief.openHint": "Opens the AI planning assistant",
            "ai.brief.error": "AI brief status",
            "ai.brief.manageSubscription": "View subscription",
            "ai.brief.configureProvider": "Configure your API key",
            "ai.brief.generatePlan": "Build a plan",
            "ai.brief.helpPrioritize": "Help me prioritize",
            "ai.brief.breakdown": "Break down a goal",
            "ai.brief.planPrefill": "Build an actionable plan from today's tasks.",
            "ai.brief.prioritizePrefill": "Help me prioritize today's tasks and explain the most important tradeoff.",
            "ai.brief.breakdownPrefill": "Break my most important goal today into actionable steps.",
            "ai.brief.localPriority": "Finish \"%@\" first, then move to lower-energy work.",
            "ai.brief.emptySummary": "There are no active tasks; use the space to organize and review.",
            "ai.brief.steadyDetail": "Nothing is due within 24 hours, so you can work steadily by priority.",
            "ai.brief.deadlineDetail": "%d tasks are due within 24 hours; protect those deliveries first.",
            "ai.brief.activeEvidence": "%d active tasks",
            "ai.brief.deadlineEvidence": "%d due within 24 hours",
            "ai.brief.healthEvidence": "Current health score: %d",
            "ai.workbench.title": "AI Planning Assistant",
            "ai.workbench.subtitle": "Turn an idea into the next step",
            "ai.workbench.service": "AI service",
            "ai.workbench.service.custom": "Your API key",
            "ai.workbench.service.managed": "Managed AI",
            "ai.workbench.service.local": "On-device planner",
            "ai.workbench.result.local": "This result · On-device",
            "ai.workbench.status.configured": "Configured",
            "ai.workbench.status.managedQuota": "Managed quota",
            "ai.workbench.status.remoteSuccess": "Latest remote request succeeded",
            "ai.workbench.status.localFallback": "Latest result used on-device fallback",
            "ai.workbench.status.quotaExceeded": "Managed quota exhausted",
            "ai.workbench.status.remaining": "%d of %d managed requests remaining.",
            "ai.workbench.mode": "Work mode",
            "ai.workbench.todayPlan": "Today Plan",
            "ai.workbench.breakdown": "Break Down",
            "ai.workbench.review": "Review",
            "ai.workbench.context": "Task context",
            "ai.workbench.contextSummary": "Using %d tasks, %d deadlines, and your current health score of %d.",
            "ai.workbench.contextDetail": "%d to do · %d in progress · %d completed",
            "ai.workbench.noAutomaticChanges": "Suggestions only; tasks are never changed, deleted, or reordered automatically.",
            "ai.workbench.todayPlanQuestion": "What is most worth moving forward today?",
            "ai.workbench.breakdownQuestion": "Which goal should become actionable next steps?",
            "ai.workbench.reviewQuestion": "What should this review help you see clearly?",
            "ai.workbench.todayPlanPlaceholder": "Add today's time, energy, or must-finish constraints",
            "ai.workbench.breakdownPlaceholder": "Describe the goal, context, and desired outcome",
            "ai.workbench.reviewPlaceholder": "Add progress, blockers, or a tradeoff to examine",
            "ai.workbench.todayPlanChip.focus": "Limit it to 3 tasks",
            "ai.workbench.todayPlanChip.buffer": "Leave buffer time",
            "ai.workbench.todayPlanChip.deadlines": "Protect near deadlines",
            "ai.workbench.breakdownChip.smallSteps": "Use 30-minute steps",
            "ai.workbench.breakdownChip.risks": "Call out risks",
            "ai.workbench.breakdownChip.verify": "Make each step verifiable",
            "ai.workbench.reviewChip.progress": "Summarize progress",
            "ai.workbench.reviewChip.blockers": "Find the main blocker",
            "ai.workbench.reviewChip.next": "Give me one next step",
            "ai.workbench.goalA11y": "AI planning goal and additional guidance",
            "ai.workbench.generatePlan": "Generate today's advice",
            "ai.workbench.generateBreakdown": "Break it down",
            "ai.workbench.generateReview": "Generate review",
            "ai.workbench.loading": "Generating suggestions",
            "ai.workbench.loadingDetail": "Using your current tasks, deadlines, and health score to shape the result.",
            "ai.workbench.result": "AI suggestions",
            "ai.workbench.result.retained": "Previous result retained",
            "ai.workbench.result.stale": "Inputs changed · Previous result",
            "ai.workbench.resultReady": "AI suggestions are ready.",
            "ai.workbench.emptyResult": "There are no suggestions to show. Add guidance and regenerate.",
            "ai.workbench.error": "Could not generate suggestions",
            "ai.workbench.retry": "Try again",
            "ai.workbench.regenerate": "Regenerate",
            "ai.workbench.addToToday": "Add to Today (%d)",
            "ai.workbench.addToTodo": "Add to Tasks (%d)",
            "ai.workbench.appliedToToday": "Added %d items to Today.",
            "ai.workbench.imported": "Imported %d AI suggestions.",
            "ai.workbench.confirmation.today": "Today Plan updated (%d items).",
            "ai.workbench.confirmation.tasks": "Added %d items to Tasks.",
            "ai.workbench.selected": "Selected",
            "ai.workbench.notSelected": "Not selected",
            "ai.workbench.minutes": "%d min",
            "ai.workbench.priority": "Priority %d",
            "ai.workbench.dueDate": "Due %@",
            "ai.workbench.existingTaskReason": "Based on the existing task priority and due date.",
            "ai.workbench.localPlanOverview": "Focus on the most important work and leave room for change.",
            "ai.workbench.defaultGoal": "the current goal",
            "ai.workbench.defineDone": "Define what done means for \"%@\"",
            "ai.workbench.collectContext": "Collect the available context, constraints, and risks",
            "ai.workbench.buildMinimum": "Build the smallest verifiable version",
            "ai.workbench.verifyResult": "Verify the result and record the next step",
            "ai.workbench.localReason": "An actionable step generated by the local planner.",
            "ai.workbench.localBreakdownOverview": "Turn the goal into small, verifiable steps first.",
            "ai.workbench.localReviewOverview": "A local review based on the current task state.",
            "ai.workbench.progress": "Progress",
            "ai.workbench.progressBody": "%d unarchived tasks completed.",
            "ai.workbench.next": "Next step",
            "ai.workbench.nextBody": "Choose the highest-priority task, define done, and move it forward.",
            "ai.workbench.nextPrompt": "Suggested AI prompt",
            "ai.workbench.nextPromptBody": "Review my current tasks, identify the highest-value next step, and explain the tradeoff.",

            "ai.status.noGoal": "Enter a goal or idea first.",
            "ai.status.breakdownBusy": "Calling AI to split tasks...",
            "ai.status.breakdownLocal": "Using local planner...",
            "ai.status.saved": "Saved",
            "ai.status.breakdownResult": "Generated %d tasks, ready to add to todo.",
            "ai.status.summaryBusy": "Generating review...",
            "ai.status.summaryLocal": "Using local review generator...",
            "ai.status.summaryDone": "Review generated.",
            "ai.status.planBusy": "Generating today's plan...",
            "ai.status.planLocal": "Using local plan generator...",
            "ai.status.planDone": "Today's plan generated.",
            "ai.status.noImport": "No AI tasks available. Run \"AI Breakdown\" first.",
            "ai.status.imported": "AI tasks added to todo.",

            "ai.provider": "AI Provider",
            "ai.baseUrl": "Base URL (OpenAI compatible)",
            "ai.model": "Model",
            "ai.model.custom": "Custom model",
            "ai.managedFixedModel": "Without an API key, managed quota uses the fixed DeepSeek V4 Flash model.",
            "ai.modelSelectorHint": "Choose a common model for this provider, or enter a custom model.",
            "ai.customModelPlaceholder": "Enter custom model ID",
            "ai.customBaseURLHint": "A custom provider requires an OpenAI-compatible Base URL.",
            "ai.key": "API Key",
            "ai.keyNoConfig": "No key configured. AI features will use the local planner.",
            "ai.keyConfigured": "Key configured. AI features will call the selected provider.",
            "ai.keySaveFailed": "The API key could not be saved to Keychain. The previous value was restored.",
            "ai.error.requestFailed": "AI request failed (%d): %@",
            "ai.error.empty": "Empty AI output, please retry.",
            "ai.error.noBaseURL": "Please fill in the Base URL.",
            "ai.error.noModel": "Please fill in the model name.",

            "purchase.fetchFailed": "Product fetch failed: %@",
            "purchase.success": "Purchase successful",
            "purchase.verifyFailed": "Purchase verification failed",
            "purchase.cancelled": "Purchase cancelled",
            "purchase.pending": "Purchase pending",
            "purchase.failed": "Purchase failed: %@",
            "purchase.restoreFailed": "Restore failed: %@",
            "purchase.registrationUnavailable": "Your Apple subscription is active. Managed AI is not configured yet; registration will retry on the next entitlement refresh.",
            "purchase.registrationRetry": "Your Apple subscription remains active. Managed AI registration will retry on the next entitlement refresh.",
            "purchase.refreshRegistration": "Refresh entitlement and retry",

            "banner.freeDesc": "This is a free preview. Subscribe to unlock instantly.",
            "banner.unlockNow": "Unlock now",

            "taskType.personal": "Personal",
            "taskType.code": "Code",
            "taskType.product": "Product",
            "taskType.learning": "Learning",
            "taskType.life": "Life",

            "health.wait": "Waiting for tasks",
            "health.good": "Great pace",
            "health.forward": "Steady progress",
            "health.context": "Add more context",
            "health.breakdown": "Break down further",

            "buddy.settings": "Companion",
            "buddy.name": "Buddy name",
            "buddy.greeting": "Greeting on launch",
            "buddy.directWrite": "Direct read/write",
            "buddy.comingSoon": "Coming soon",
            "buddy.placeholder": "Say something...",
            "buddy.noMemory": "(No conversations yet)",
            "buddy.silent": "(I went quiet for a moment. Let's talk again soon.)",
            "buddy.send": "Send",
            "buddy.addTodo": "Add to todos",
            "buddy.addedTodo": "Added to todo ✓",
            "buddy.completed": "Marked done ✓",
            "buddy.splitTask": "Split and added to todo ✓",

            "notification.dueTitle": "Task due",
            "notification.dueBody": "\"%@\" is due today",
            "noticeTitle": "Reminders",
            "noticeEnable": "Enable reminders",
            "noticeEnabled": "Reminders enabled",
            "noticeDenied": "Notifications are blocked — tap to re-enable",
            "notice.systemStatus": "System permission",
            "notice.systemAllowed": "Allowed",
            "notice.systemDenied": "Notifications not allowed",
            "notice.systemNotDetermined": "Not requested yet",
            "notice.openSettings": "Open Settings",
            "notice.permissionExplanation": "When enabled, only incomplete tasks with due dates send reminders. Turning it off removes pending task reminders.",
            "notice.debugPendingCount": "%d pending task reminders (Debug)",

            // Quota (managed AI quota)
            "quota.exceeded.free": "Free quota used up: subscribe to Pro or add your own API key",
            "quota.exceeded.daily": "Daily quota used up — try again tomorrow",
            "quota.exceeded.other": "Quota limited: %@",
            "quota.missingBaseURL": "AI quota service not configured",
            "quota.server": "AI service error (%d %@)",

            // Voice (companion voice input)
            "voice.micA11y": "Voice input",
            "voice.stopRecording": "Stop recording",
            "voice.speechUnavailable": "Speech recognition unavailable",
            "voice.micPermissionDenied": "Microphone/speech permission denied — enable it in Settings",
            "voice.sessionFailed": "Recording session failed: %@",
            "voice.engineFailed": "Recording engine failed: %@",
            "voice.errorTitle": "Voice input unavailable",
            "voice.switchToVoice": "Switch to voice input",
            "voice.switchToKeyboard": "Switch to keyboard input",
            "voice.cancelAndSwitchToKeyboard": "Cancel voice input and switch to keyboard",
            "voice.startRecording": "Tap to start speaking",
            "voice.requestingPermission": "Requesting voice permission…",
            "voice.recording": "Listening — tap to finish",
            "voice.finalizing": "Finishing transcription…",
            "voice.openSettings": "Open Settings",
            "voice.speechPermissionDenied": "Speech recognition permission was denied. Enable it in Settings.",
            "voice.microphonePermissionDenied": "Microphone permission was denied. Enable it in Settings.",
            "voice.recognitionFailed": "Speech recognition failed. Please try again.",
            "voice.noSpeechDetected": "No speech was detected. Please try again.",
            "voice.transcriptReady": "Voice text is in the composer. Review it before sending.",
        ],
    ]

    static func t(_ key: String) -> String {
        let lang = currentLanguage
        return table[lang]?[key] ?? table["zh"]?[key] ?? key
    }

    static func t(_ key: String, _ args: CVarArg...) -> String {
        let value = t(key)
        return String(format: value, arguments: args)
    }

    static func hasTranslation(_ key: String, language: String) -> Bool {
        table[language]?[key] != nil
    }

    static var currentLanguage: String {
        UserDefaults.standard.string(forKey: languageKey) ?? "zh"
    }

    static func setLanguage(_ language: String) {
        UserDefaults.standard.set(language, forKey: languageKey)
    }
}
